package time.analyser;

public enum DateType {
    MILLIARD, ILYA, JC, NEARJC, NEARJC2,NEARJC3, NEARLESS, ROMAN, ANNEE2DOT, PRECISE, DOUBLEPARENTHESIS2, DOUBLEPARENTHESIS, TIRET, JC_ENTRE, JC_ENTRE_SUITE, JC_PREV, TIRET2
}