version: '2'
services:
  time-api:
    image: blueforest/histoires-api:latest
    environment:
      indexDir: /lucene
      port: '8080'
      searchPhrasePageSize: '50'
    stdin_open: true
    volumes:
    - /var/log/time:/var/log/time
    - /var/lib/time/lucene:/lucene
    tty: true
    labels:
      io.rancher.container.pull_image: always
  time-web:
    image: blueforest/time.front:1.0.1
    environment:
      PORT: '80'
    ports:
      - "1515:80"
      - "1543:443"
    stdin_open: true
    tty: true
    links:
    - time-api:time-api
    labels:
      io.rancher.container.pull_image: always