version: '3.3'
services:

  histoires-web:
    image: "blueforest/histoires-web:latest"
    ports:
      - "80:80"
    links:
      - histoires-api
    restart: always

  histoires-api:
    image: "blueforest/histoires-api:latest"
    expose:
     - "8080"
    environment:
      - indexDir=/lucene
      - port=8080
      - searchPhrasePageSize=50
    volumes:
      - /var/log/time:/var/log/time
      - /var/lib/time/lucene:/lucene
    restart: always
